package com.imesong.springdream.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "category".
 */
public class Category {

    private long id;
    /**
     * Not-null value.
     */
    private String name;
    private Integer parent;
    private String pinxin;
    private Integer sequence;
    private Boolean del;

    public Category() {
    }

    public Category(long id) {
        this.id = id;
    }

    public Category(long id, String name, Integer parent, String pinxin, Integer sequence, Boolean del) {
        this.id = id;
        this.name = name;
        this.parent = parent;
        this.pinxin = pinxin;
        this.sequence = sequence;
        this.del = del;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public Integer getParent() {
        return parent;
    }

    public void setParent(Integer parent) {
        this.parent = parent;
    }

    public String getPinxin() {
        return pinxin;
    }

    public void setPinxin(String pinxin) {
        this.pinxin = pinxin;
    }

    public Integer getSequence() {
        return sequence;
    }

    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    public Boolean getDel() {
        return del;
    }

    public void setDel(Boolean del) {
        this.del = del;
    }

}
