package com.imesong.springdream.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoryDaoConfig;
    private final DaoConfig dreamDaoConfig;

    private final CategoryDao categoryDao;
    private final DreamDao dreamDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        dreamDaoConfig = daoConfigMap.get(DreamDao.class).clone();
        dreamDaoConfig.initIdentityScope(type);

        categoryDao = new CategoryDao(categoryDaoConfig, this);
        dreamDao = new DreamDao(dreamDaoConfig, this);

        registerDao(Category.class, categoryDao);
        registerDao(Dream.class, dreamDao);
    }

    public void clear() {
        categoryDaoConfig.getIdentityScope().clear();
        dreamDaoConfig.getIdentityScope().clear();
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public DreamDao getDreamDao() {
        return dreamDao;
    }

}
