package com.imesong.springdream.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.quinny898.library.persistentsearch.SearchResult;

/**
 * Entity mapped to table "dream".
 */
public class Dream extends SearchResult {

    private long id;
    private Integer category1;
    private Integer category2;
    /**
     * Not-null value.
     */
    private String name;
    /** Not-null value. */
    private String content;
    private Boolean del;
    private Boolean recommend;
    private Integer sequence;
    private Integer hit;
    private Integer is_long;

    public Dream() {
    }

    public Dream(long id) {
        this.id = id;
    }

    public Dream(long id, Integer category1, Integer category2, String name, String content, Boolean del, Boolean recommend, Integer sequence, Integer hit, Integer is_long) {
        super(name);
        this.id = id;
        this.category1 = category1;
        this.category2 = category2;
        this.name = name;
        this.content = content;
        this.del = del;
        this.recommend = recommend;
        this.sequence = sequence;
        this.hit = hit;
        this.is_long = is_long;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Integer getCategory1() {
        return category1;
    }

    public void setCategory1(Integer category1) {
        this.category1 = category1;
    }

    public Integer getCategory2() {
        return category2;
    }

    public void setCategory2(Integer category2) {
        this.category2 = category2;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(String content) {
        this.content = content;
    }

    public Boolean getDel() {
        return del;
    }

    public void setDel(Boolean del) {
        this.del = del;
    }

    public Boolean getRecommend() {
        return recommend;
    }

    public void setRecommend(Boolean recommend) {
        this.recommend = recommend;
    }

    public Integer getSequence() {
        return sequence;
    }

    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    public Integer getHit() {
        return hit;
    }

    public void setHit(Integer hit) {
        this.hit = hit;
    }

    public Integer getIs_long() {
        return is_long;
    }

    public void setIs_long(Integer is_long) {
        this.is_long = is_long;
    }

    @Override
    public String toString() {
        return "id:" + id + "\tname:"+name;
    }
}
