package com.imesong.springdream.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DREAM".
 */
public class Dream {

    private Long id;
    private String category1;
    private String category2;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String content;
    private String del;
    private String recommend;
    private String sequence;
    private String hit;
    private Integer is_long;

    public Dream() {
    }

    public Dream(Long id) {
        this.id = id;
    }

    public Dream(Long id, String category1, String category2, String name, String content, String del, String recommend, String sequence, String hit, Integer is_long) {
        this.id = id;
        this.category1 = category1;
        this.category2 = category2;
        this.name = name;
        this.content = content;
        this.del = del;
        this.recommend = recommend;
        this.sequence = sequence;
        this.hit = hit;
        this.is_long = is_long;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCategory1() {
        return category1;
    }

    public void setCategory1(String category1) {
        this.category1 = category1;
    }

    public String getCategory2() {
        return category2;
    }

    public void setCategory2(String category2) {
        this.category2 = category2;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(String content) {
        this.content = content;
    }

    public String getDel() {
        return del;
    }

    public void setDel(String del) {
        this.del = del;
    }

    public String getRecommend() {
        return recommend;
    }

    public void setRecommend(String recommend) {
        this.recommend = recommend;
    }

    public String getSequence() {
        return sequence;
    }

    public void setSequence(String sequence) {
        this.sequence = sequence;
    }

    public String getHit() {
        return hit;
    }

    public void setHit(String hit) {
        this.hit = hit;
    }

    public Integer getIs_long() {
        return is_long;
    }

    public void setIs_long(Integer is_long) {
        this.is_long = is_long;
    }

}
